### ISSUE TITLE
[BUG] NullPointerException in EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by Nukecraft5419** [Bermiin/StrikeDeathMessages#10]
**Errors:**
https://mclo.gs/bI9HOLH

**Server version & software:**
Please include the name of your spigot or paper fork if you are using one.
 - LightSpigot 1.8.8
 
**StrikePractice version:**
 - 3.8.1

**Additional context**
It also gives errors when I change its says its not that one however if I stay the default one that error comes up when one dies in addition to creating double messages of the death and respawn timer

**Comment by Bermiin** [comment]
Fixed in the latest release (https://github.com/Bermiin/StrikeDeathMessages/releases/tag/v1.7.1)

**Comment by Nukecraft5419** [comment]
Thanks, I will test it to see if there are any other bugs
