### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by josegoust** [Bermiin/StrikeDeathMessages#12]
**Describe the bug**

**How To Reproduce**
The plugin dont work in 1.21 paperspigot

**Errors:**
Please use [MCLogs](https://mclo.gs) or a pastebin service of your choice when reporting errors.

**Screenshots:**

**Server version & software:**
Please include the name of your spigot or paper fork if you are using one.
 - PaperSpigot 1.21
 
**StrikePractice version:**
 - latest dev build

**Comment by Bermiin** [comment]
Can you please be a little bit specific as to how exactly does it not work? Do you have any errors in the console?

**Comment by Bermiin** [comment]
No response after 3 weeks, no additional info provided either.

Try using latest release and if you are still gonna have the same error, open a new issue
