### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Shadowjpg02** [Bermiin/StrikeDeathMessages#8]
**Describe the bug**
So in the bridge mode from what I understand while you kill an enemy even before killing him the death chat message already comes out and then when you kill him again, it happens sometimes even with the void, or if not directly it happens many times even when he doesn't appear before you kill him but when you kill him he appears more than once

**How To Reproduce**
You simply kill the enemy in the bridge mode or you fall into the void and the message appears more than once, but it doesn't always happen

**Expected behavior**
I expected the message to only come out once

**Errors:**
It doesn't give any errors

**Screenshots:**
https://i.imgur.com/TZRtYs5.png

**Server version & software:**
Please include the name of your spigot or paper fork if you are using one.
 - pSpigot 1.8.8 But first there was FoxSpigot 1.8.8 and it still gave this problem, then I tried with paper 1.8.8 and it still gave this problem and then I tried with pSpigot 1.8.8 and it still gave this problem
 
**StrikePractice version:**
 - 3.8.1

**Additional context**
I have nothing to add

**Comment by Bermiin** [comment]
Fixed in latest release
